#!/usr/bin/env pyston3

import argparse
import logging
import os
import os.path
import sys
import traceback

sys.path.insert(0, os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..')))
import mango  # nopep8

# We explicitly want argument parsing to be outside the main try-except block because some arguments
# (like --help) will cause an exit, which our except: block traps.
parser = argparse.ArgumentParser(
    description="Run the Transaction Scout to display information about a specific transaction.")
mango.Context.add_context_command_line_parameters(parser)
parser.add_argument("--id-file", type=str, default="id.json",
                    help="file containing the JSON-formatted wallet private key")
parser.add_argument("--signature", type=str, required=True,
                    help="The signature of the transaction to look up")
parser.add_argument("--log-level", default=logging.WARNING, type=lambda level: getattr(logging, level),
                    help="level of verbosity to log (possible values: DEBUG, INFO, WARNING, ERROR, CRITICAL)")
args = parser.parse_args()

logging.getLogger().setLevel(args.log_level)
logging.warning(mango.WARNING_DISCLAIMER_TEXT)

try:
    signature = args.signature

    context = mango.Context.from_context_command_line_parameters(args)

    logging.info(f"Context: {context}")
    logging.info(f"Signature: {signature}")

    report = mango.TransactionScout.load(context, signature)
    print(report)
except Exception as exception:
    logging.critical(f"transaction-scout stopped because of exception: {exception} - {traceback.format_exc()}")
except:
    logging.critical(f"transaction-scout stopped because of uncatchable error: {traceback.format_exc()}")
